[package]
name = "ssl-log-tools"
version = "0.1.0"
authors = ["Devin Schwab <digidevin@gmail.com>"]
edition = "2018"

[build-dependencies]
glob = { version = "0.2" }
protoc-rust = "2.2"

[dependencies]
failure = { version = "0.1" }
protobuf = { version = "2.3" }

[dev-dependencies]
proptest = "0.9"
tempfile = "3"
